### ISSUE TITLE
Error while running glee on Windows

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#222]
Operating system: Windows 11
Node: 14
#### Describe the bug
When I try to run a project generated by glee using `npm run dev` command it shows this error:
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:791:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at file:///C:/Users/.../glee/src/lib/functions.js:27:35
    at Array.map (<anonymous>)
    at register (file:///C:/Users/.../node_modules/@asyncapi/glee/src/lib/functions.js:17:49)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
⚡ Server websockets is ready to accept connections.
```
After trying to hit the endpoint with `websocat` I get this error:

```
↙ hello was received from websockets
'Hello\r\n'
x functions[operationId].run is not a function
    at file:///C:/Users/.../node_modules/@asyncapi/glee/src/lib/runtimes/js.js:14:8
    at new Promise (<anonymous>)
    at runJS (file:///C:/Users/.../bot-the-savior/node_modules/@asyncapi/glee/src/lib/runtimes/js.js:12:10)
    at triggerFunction (file:///C:/Users/.../node_modules/@asyncapi/glee/src/lib/runtimes/index.js:26:17)
    at Function.<anonymous> (file:///C:/Users/.../node_modules/@asyncapi/glee/src/index.js:70:11)
    at file:///C:/Users/.../node_modules/@asyncapi/glee/src/lib/glee.js:155:17   
    at C:\Users\...\node_modules\async\dist\async.js:1987:20
    at C:\Users\...\node_modules\async\dist\async.js:1928:13
    at replenish (C:\Users\...\node_modules\async\dist\async.js:446:21)
    at C:\Users\...\node_modules\async\dist\async.js:451:13

```
#### How to Reproduce
1) run `npx create-glee-app`
2) go to the app folder.
2) run `npm run dev`

#### Expected behaviour
It shouldn't show any error and run as demonstrated.

cc: @fmvilas @jonaslagoni

**Comment by KhudaDad414** [comment]
This issue has been resolved by upgrading the `node` version to `17`. feel free to close this if it is not relevant anymore.

**Comment by sudoshreyansh** [comment]
I used node v17.3.0 but the error still exists.

**Comment by fmvilas** [comment]
That's weird. It's working well for me 🤔
