### ISSUE TITLE
Glee is crashing when I pass custom server from config file. 

### ISSUE THREAD

**Issue by Souvikns** [asyncapi/glee#436]
#### Describe the bug
I am trying to use expressjs with glee, to see how well it would work and for that I need to pass in a custom HTTP server with an express app object, when I pass in the custom server glee crashed and throws this error 

```
⚡ Server websockets is ready to accept connections.
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at getOrSetAsyncId (node:internal/async_hooks:423:7)
    at Object.connectionListener [as connection] (node:_http_server:596:5)
    at file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:121:60
    at Generator.next (<anonymous>)
    at file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:3:12)
    at resolveFunctions (file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:115:45)
    at file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:118:13
    at Generator.next (<anonymous>)
    at file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:3:12)
    at resolveFunctions (file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:115:45)
    at file:///Users/postman/Documents/Learning/glee-custom-server/node_modules/@asyncapi/glee/dist/lib/util.js:118:13

```

#### How to Reproduce
Create a new glee application using asyncapi cli `asyncapi new glee` and then create a `glee.config.js` file and write this code 

```js
const express = require('express')
const http = require('http')
const app = express()
const httpServer = http.createServer()

httpServer.listen(8000)

module.exports = () => {
    return {
        ws: {
          server: {
            httpServer: httpServer,
            port: 8000,
            adapter: 'native'
          },
          client: {}
        }
    }
}
```

#### Expected behavior
Glee should be able to take the custom server as an input and use it to run and accept messages.

**Comment by Souvikns** [comment]
I was checking what is causing the issue and found this is happening because of a util function `resolveFunctions` which is used to parse the config to find any functions and call them, as our config accepts both objects and functions. When I remove this from the code and access the config directly from the glee object it works. 

https://github.com/asyncapi/glee/blob/a00a1e7da6493d307aad776fbe18451abae5d8d0/src/lib/util.ts#L131-L139
