### ISSUE TITLE
Bug in MQTT Adapter post refactoring

### ISSUE THREAD

**Issue by kaushik-rishi** [asyncapi/glee#442]
#### Describe the bug
- reference the **how to reproduce** section for the inital steps
- The bug
```
TypeError: Cannot read properties of undefined (reading 'channels')
    at MqttAdapter.<anonymous> (file:///home/darkangel/Desktop/asyncapi/glee/dist/lib/adapter.js:43:86)
    at MqttAdapter.emit (node:events:513:28)
    at MqttAdapter.emit (node:domain:489:12)
    at MqttClient.<anonymous> (file:///home/darkangel/Desktop/asyncapi/glee/dist/adapters/mqtt/index.js:87:22)
    at MqttClient.emit (node:events:513:28)
    at MqttClient.emit (node:domain:489:12)
    at MqttClient._handlePublish (/home/darkangel/Desktop/asyncapi/glee/node_modules/mqtt/lib/client.js:1547:12)
    at MqttClient._handlePacket (/home/darkangel/Desktop/asyncapi/glee/node_modules/mqtt/lib/client.js:535:12)
    at work (/home/darkangel/Desktop/asyncapi/glee/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/home/darkangel/Desktop/asyncapi/glee/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/home/darkangel/Desktop/asyncapi/glee/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/home/darkangel/Desktop/asyncapi/glee/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at Writable.write (/home/darkangel/Desktop/asyncapi/glee/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:302:11)
```

#### How to Reproduce
- Not sure if you'll be able to reproduce, because some of my friends got an MQTT server running (@KhudaDad414 said he had an MQTT server running along with current version as well)
- Irrespective i'll share how to reproduce
- run `examples/social-network/notifications-service`
- you will not see the `⚡ Connected to server mosquitto.` in the output meaning it hasn't connected properly with the MQTT server.
- if you still push a message using `docker run -it hivemq/mqtt-cli pub -t post/liked -m '{"userId": 1, "postId": 10}' -h test.mosquitto.org`
- you'll be able to get the error, referenced in **describe the bug** section

#### The actual problem and how it occurred
- This is solely based on my debugging of the issue (with great help from @KhudaDad414 :slightly_smiling_face:  )
- Conclusion
    - Problem with mqtt adapter.
    - https://github.com/asyncapi/glee/blob/master/src/adapters/mqtt/index.ts#L174
    - This line is supposed to be `if (!this.firstConnect) {`
    - Checking the [blame](https://github.com/asyncapi/glee/blame/master/src/adapters/mqtt/index.ts#L174), it was changed during a [refactor](https://github.com/asyncapi/glee/pull/400), the [PR diff](https://github.com/asyncapi/glee/commit/92476cbdd167060a0fa3c5b7a25276dfc5c6c36b#diff-a175350b71a8d6f6643e2541137fd5cd81fd9a4837ed2bcce8af24f8627046ecR174), Could be more helpful if @oviecodes took a look and confirmed this as well. :slightly_smiling_face: 

- How i got to the conclusion (approach could help someone :smile: )
    - I wasn't getting the response of `⚡ Connected to server mosquitto.` and the error was in the `[lib/adapter.js](https://github.com/asyncapi/glee/blob/master/src/lib/adapter.ts#L55)` file.
    - Reading the error it was clear that it actually meant no connection was pushed to `this._connections`. 
    - The connection was supposed to be pushed [here](https://github.com/asyncapi/glee/blob/master/src/lib/adapter.ts#L88)
    - Which means the event is not being emitted, it is supposed to be emitted [here](https://github.com/asyncapi/glee/blob/master/src/adapters/mqtt/index.ts#L176) 
    - That's where i saw that `this.checkFirstConnect` is being checked which is a function and not the intended boolean, it was correctly written before the refactoring PR -> [reference](https://github.com/asyncapi/glee/blob/799e754ff9/src/adapters/mqtt/index.ts#L103)

#### Expected behavior
Should connect to the MQTT server and return `⚡ Connected to server mosquitto.` and keep recieving further messages like this. 👇
![image](https://github.com/asyncapi/glee/assets/52498617/1f42ebf0-3b7b-4f81-980b-1246e98177ca)

I understand that i could be completely wrong here, Please feel free to criticize. :slightly_smiling_face:.

**Comment by kaushik-rishi** [comment]
I haven't taken any confirmation from the maintainers/code owners if the issue is correct or not, But incase it's the actual problem, Very humbly, i'm linking a PR to fix it.

**Comment by oviecodes** [comment]
Thanks for bringing this to my attention @kaushik-rishi , I'll take a look at it.

**Comment by kaushik-rishi** [comment]
@oviecodes i did create a PR.
