### ISSUE TITLE
Client security doesn't work with v3 of the spec

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#556]
#### Describe the bug
Consider this AsyncAPI file:
```yaml
asyncapi: 3.0.0
info:
  title: Slack Websocket API
  version: 1.0.0
servers:
  OpenAI:
    host: api.openai.com
    protocol: https
    security:
      - $ref: "#/components/securitySchemes/openAI"
.
.
.
components:
  securitySchemes:
    openAI:
      type: http
      scheme: bearer
```

when I use this asyncapi file with the following auth function:
```js
export async function clientAuth({ parsedAsyncAPI, serverName }) {
  return {token: process.env.CHAT_API}
}
```

I get the following error:
```bash
x Cannot read properties of undefined (reading 'json')
    at file:....dist/lib/wsHttpAuth.js:31:78
    at Array.map (<anonymous>)
    at GleeAuth.checkClientAuthConfig (file://...dist/lib/wsHttpAuth.js:26:63)
    at GleeAuth.<anonymous> (file:///....dist/lib/wsHttpAuth.js:148:35)
    at Generator.next (<anonymous>)
    at fulfilled (file://....dist/lib/wsHttpAuth.js:4:58)

```

#### How to Reproduce
Creat an http client and try to use the `bearer` authentication method.

#### Expected behavior
It should authenticate the client as expected.

cc: @oviecodes

**Comment by oviecodes** [comment]
I'll take a look at it @KhudaDad414 .

**Comment by Souvikns** [comment]
@oviecodes let me take this one

**Comment by oviecodes** [comment]
okay @Souvikns

**Comment by Souvikns** [comment]
After playing with the codebase I found that the errors are originating from https://github.com/asyncapi/glee/blob/25ab9162b5ad6f216f5f86894b136d0c91274891/src/lib/wsHttpAuth.ts#L31
This function basically tries to check if `auth config` provided from the `auth` function match the spec, but now with V3 the way of accessing the config has changed and thus it fails to read the spec for `security schemes` and thus get undefined errors. 


There is also a problem with the logic we are using for providing and parsing `security schemes`, since this changed a lot from V2 to V3 of the spec. 

Security for spec V2
```yaml
security:
    - token: []
    - userPass: []
    - apiKey: []
    - UserOrPassKey: []
    - oauth: 
      - write:pets
      - read:pets

```

Security for spec V3
```yaml
servers:
  OpenAI:
    host: api.openai.com
    protocol: https
    security:
      - $ref: '#/components/securitySchemes/openAI'
components:
  securitySchemes:
    openAI:
      type: http
      scheme: bearer
      name: token
```

Currently, we are providing the `security parameters` according to the `type`, something like this -

```ts
export async function clientAuth({ serverName }) {
    console.log("serverName", serverName)
  
    return {
      token: process.env.TOKEN,
      oauth: process.env.OAUTH2,
      apiKey: process.env.APIKEY,
      userPass: {
        user: process.env.USERNAME,
        password: process.env.PASSWORD
      }
    }
  }

```
This is not possible with the spec v3 and also there are better ways of passing in the parameters now. 

---

I think one way to solve this issue, is by modifying both the `clientAuth` function and the way we parse `securitySchemes`. 

### Parsing 

Now we should parse the `securityScheme` according to the `id` provided by the parser, and check for `type` and `name` to determine what parameter to fetch and where to pass in the provider. 


### Auth Function 

Instead of passing the authentication parameters according to the type of the `securityScheme` we should pass it according to the id and use the name property to pass in the actual parameter, so it would look something like this 

```ts
async function clientAuth({serverName}) {
  return {
    openAI: {
      token: process.env.TOKEN
    }
  }
}

```


> @KhudaDad414 and @oviecodes let me know your thoughts on this.

**Comment by KhudaDad414** [comment]
@Souvikns, your purposed solution makes sense to me. 👍 
I guess it makes more sense to discuss it over a PR.

**Comment by oviecodes** [comment]
Yeah, @Souvikns , but how do we handle people that will use spec v2? or are we suppose to support just v3 and later going forward

**Comment by Souvikns** [comment]
/progress 60

Opened [PR](https://github.com/asyncapi/glee/pull/588), depends on https://github.com/asyncapi/glee/pull/551 as cannot update the HTTP examples without request/reply support.
