### ISSUE TITLE
Authentication fails with httpApiKey

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/glee#591]
#### Describe the bug
I am trying to authenticate against the [slack socket mode](https://api.slack.com/apis/connections/socket) websocket server but glee throw this error:

```
TypeError: Cannot read properties of undefined (reading 'json')
    at file:///Users/rktrees/request-reply/dist/lib/wsHttpAuth.js:28:78
    at Array.map (<anonymous>)
    at GleeAuth.checkClientAuthConfig (file:///Uyncapi/glee.worktrees/request-reply/dist/lib/wsHttpAuth.js:25:63)
    at GleeAuth.<anonymous> (file:/ees/request-reply/dist/lib/wsHttpAuth.js:145:35)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Ust-reply/dist/lib/wsHttpAuth.js:4:58)
```

> asyncapi.yaml

```yaml
asyncapi: 3.0.0
info:
  title: Slack Websocket and OpenAI API
  version: 1.0.0
...
  Slack_WebSocket:
    host: wss-primary.slack.com
    pathname: /link/
    protocol: wss
    security:
      - $ref: '#/components/securitySchemes/app_id'
      - $ref: '#/components/securitySchemes/token'
...
components:
  securitySchemes:
    token:
      type: httpApiKey
      name: ticket
      in: query
    app_id:
      type: httpApiKey
      name: app_id
      in: query
...
x-remoteServers: 
  - Slack_WebSocket
```

> auth/Slack_WebSocket.ts

```ts
export const clientAuth = () => {
  return {
    ticket: '3863c5be0b173c',
    app_id: 'b02112d9364c32efb98f'
  }
}
```

cc: @Souvikns @oviecodes

**Comment by oviecodes** [comment]
@KhudaDad414 it's all the same bug, the issues stems from using asyncAPI version 3 rather than  version 2, so the fix @Souvikns is working on should resolve it.

**Comment by KhudaDad414** [comment]
@oviecodes sorry, I thought we merged this: https://github.com/asyncapi/glee/pull/588 🤦

**Comment by Souvikns** [comment]
@KhudaDad414 I think this one is solved should we close this?

**Comment by KhudaDad414** [comment]
@Souvikns definitly.
