### ISSUE TITLE
Update Kafka Adapter to support spec v3

### ISSUE THREAD

**Issue by oviecodes** [asyncapi/glee#673]
#### Describe the bug
We need to update the kafka adapter to support v3 of the spec. Currently, from what I noticed, the parsed methods seem to be different from v2 and it causes the adapter to fail. 

#### How to Reproduce
Update the spec to v3 and run the project in the `examples/kafka-test` directory. First, you'll get an error related to the `reply.channel`(I'll have to check more, I'm slightly confused by the reply feature). However, we can get past that by adding a conditional to check for `reply`. Finally once the `reply.channel` error out of the way, you'll get the following error

`TypeError: Cannot read properties of undefined (reading 'type')
    at file:///Users/a/Documents/asyncapi/glee/dist/adapters/kafka/index.js:29:87
    at Array.find (<anonymous>)
    at KafkaAdapter.<anonymous> (file:///Users/a/Documents/asyncapi/glee/dist/adapters/kafka/index.js:29:69)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/a/Documents/asyncapi/glee/dist/adapters/kafka/index.js:4:58) `

#### Expected behavior
The Kafka adapter should start correctly without errors.

@Souvikns @KhudaDad414 I'll start working on a fix as this is `blocking #411 `.

**Comment by KhudaDad414** [comment]
Still relevant.

**Comment by oviecodes** [comment]
Still relevant.
